name: Build and Publish Package

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Install expo-module-scripts globally
        run: bun install -g expo-module-scripts
      
      - name: Build package
        run: |
          # Add node_modules/.bin to PATH
          export PATH="$PATH:$(pwd)/node_modules/.bin"
          bun run build
      
      - name: Publish to GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          echo "@dondragon2:registry=https://npm.pkg.github.com" >> .npmrc
          
          # Add node_modules/.bin to PATH
          export PATH="$PATH:$(pwd)/node_modules/.bin"
          
          # Skip prepublishOnly script and publish directly
          bun publish --registry https://npm.pkg.github.com --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 